spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.11.13:5432/misaka
    username: misaka
    password: mikoto
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 20MB